name: Build ğŸ¥–ğŸ˜­ğŸŒ­

on:
  workflow_dispatch: {}

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      # Step 1: æŸ¥çœ‹repo
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          lfs: true # ä½¿ç”¨ LFS

      # Step 2: æ¸…ç†Dockerç©ºé–“ä»¥é‡‹æ”¾ç£ç¢Ÿç©ºé–“
      - name: Clean Docker Space
        run: |
          docker system prune -af --volumes
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/unity/Editor/Data/Documentation
          sudo rm -rf /opt/unity/Editor/Data/PlaybackEngines/LinuxStandaloneSupport
          sudo rm -rf /opt/unity/Editor/Data/PlaybackEngines/AndroidPlayer
          sudo rm -rf /opt/unity/Editor/Data/PlaybackEngines/iOSSupport

      # Step 3: æ¸…ç†Unity Cacheä»¥é‡‹æ”¾é¡å¤–ç©ºé–“
      - name: Clear Unity Cache
        run: |
          rm -rf ~/.cache/unity3d

      # Step 4: (å¯é¸) CacheåŠ é€ŸBuild
      - name: Cache
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Step 5: ç”¨Game-CI Builderå»ºç½®å°ˆæ¡ˆ
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          allowDirtyBuild: true

      # Step 6: è¼¸å‡ºæˆartifact
      - uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build
          retention-days: 2  # å¹¾å¤©å¾Œæœƒåˆªé™¤
