name: Build ğŸ¥–ğŸ˜­ğŸŒ­

on:
  workflow_dispatch: {}

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      # Step 1: æŸ¥çœ‹repo
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          lfs: true # ä½¿ç”¨ LFS

      # Step 2: æ¸…ç†Dockerç©ºé–“ä»¥é‡‹æ”¾ç£ç¢Ÿç©ºé–“
      - name: Clean Docker Space
        run: |
          echo "Cleaning system to free up space..."
          docker system prune -af --volumes # æ¸…é™¤ Docker è³‡æº
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*
          sudo rm -rf /usr/local/lib/android # åˆªé™¤ Android å·¥å…·
          sudo rm -rf /opt/unity/Editor/Data/Documentation # åˆªé™¤ Unity æ–‡ä»¶
          sudo rm -rf /opt/unity/Editor/Data/PlaybackEngines/LinuxStandaloneSupport # åˆªé™¤ Linux æ”¯æ´
          sudo rm -rf /opt/unity/Editor/Data/PlaybackEngines/AndroidPlayer # åˆªé™¤ Android æ”¯æ´
          sudo rm -rf /opt/unity/Editor/Data/PlaybackEngines/iOSSupport # åˆªé™¤ iOS æ”¯æ´
          sudo rm -rf /usr/share/dotnet # ç§»é™¤æœªä½¿ç”¨çš„ .NET SDK
          sudo rm -rf /usr/local/lib/node_modules # ç§»é™¤ Node.js å¥—ä»¶
          sudo apt-get autoremove -y # è‡ªå‹•ç§»é™¤ä¸éœ€è¦çš„å¥—ä»¶
          df -h # æŸ¥çœ‹å‰©é¤˜ç©ºé–“ç‹€æ…‹

      # Step 3: æ¸…ç†Unity Cacheä»¥é‡‹æ”¾é¡å¤–ç©ºé–“
      - name: Clear Unity Cache
        run: |
          rm -rf ~/.cache/unity3d

      # Step 4: (å¯é¸) CacheåŠ é€ŸBuild
      - name: Cache
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Step 5: ç”¨Game-CI Builderå»ºç½®å°ˆæ¡ˆ
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          allowDirtyBuild: true

      # Step 6: è¼¸å‡ºæˆartifact
      - uses: actions/upload-artifact@v4
        with:
          name: Build-${{ github.run_id }}
          path: build
          retention-days: 2  # å¹¾å¤©å¾Œæœƒåˆªé™¤
