# Workflow åç¨±
name: My workflow

# è§¸ç™¼æ™‚æ©Ÿ
on:
  workflow_dispatch: {}

# åŸ·è¡Œçš„å‹•ä½œ(Job)
jobs:
  build:  # Jobåç¨±ï¼Œä¹Ÿå¯ä»¥ç”¨nameä¾†é‡æ–°å®šç¾©ğŸ‘‡
    name: Test-Job          # å®šç¾©Jobåç¨±
    runs-on: ubuntu-latest  # åœ¨å“ªå€‹å¹³å°åŸ·è¡Œ
    steps:  # Jobçš„å‹•ä½œ
      - name: Say hello     # é€™å€‹å‹•ä½œçš„åç¨±
      # uses:   # ç”¨åˆ°çš„Github Action
      # with:   # Action ç”¨åˆ°çš„åƒæ•¸
      #   parameter:
      #     .
      #     .
      #     .
        run: echo Hello     # åŸ·è¡Œçš„å‹•ä½œ